name: iforevents_clevertap
description: "CleverTap customer engagement integration for IForEvents - Advanced user analytics, segmentation, and personalized messaging."
version: 0.0.1
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents_clevertap/latest/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  clevertap_plugin: ^3.5.0
  iforevents: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
