name: iforevents
description: "A comprehensive Flutter package for event tracking and analytics integration with support for multiple platforms including Firebase, Mixpanel, and Algolia."
version: 0.0.1
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents/latest/

publish_to: 'https://pub.dev'

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  android_id: ^0.4.0
  dart_ipify: ^1.1.1
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
