name: flutter_iforevents_workspace
publish_to: none
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

resolution: workspace

workspace:
  - iforevents
  - iforevents_firebase
  - iforevents_mixpanel
  - iforevents_algolia
