name: iforevents_mixpanel
description: "Mixpanel analytics integration for IForEvents - Advanced user behavior tracking, funnel analysis, and retention insights."
version: 0.0.3
publish_to: 'none'
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents_mixpanel/latest/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  mixpanel_flutter: ^2.4.4
  iforevents:
    path: ../iforevents

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
