name: iforevents_meta
description: "Meta (Facebook) Analytics integration for IForEvents - Comprehensive marketing analytics and user behavior tracking for Facebook ecosystem."
version: 0.0.3
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents_meta/latest/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  facebook_app_events: ^0.20.1
  iforevents: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
