name: iforevents_algolia
description: "Algolia search analytics integration for IForEvents - Track search behavior, product interactions, and user engagement insights."
version: 0.0.3
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents_algolia/latest/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  algolia_insights: ^1.0.3
  iforevents: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
