name: iforevents_algolia
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/innovafour/flutter_iforevents

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  algolia_insights: ^1.0.3
  iforevents:
    git:
      url: https://github.com/innovafour/flutter_iforevents
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
